// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240907070208_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5ab19b6-3c4e-44d1-8bc9-012be5105b29"),
                            Author = "F. Scott Fitzgerald",
                            Category = "Novel",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("6162134c-3c7d-40cf-9cbc-b6fe05482bfe"),
                            Author = "J. D. Salinger",
                            Category = "Novel",
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = new Guid("81b0839d-c80f-4f08-967f-7a5c0f307265"),
                            Author = "Harper Lee",
                            Category = "Novel",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("5a5395eb-c69c-4c36-810c-941d12e66074"),
                            Author = "George Orwell",
                            Category = "Novel",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("063f7a3c-598c-42ee-9381-92a42453d596"),
                            Author = "Jane Austen",
                            Category = "Novel",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("1d1a0641-32d3-4dc6-ae02-70d81d0c3e5a"),
                            Author = "Charlotte Bronte",
                            Category = "Novel",
                            Title = "Jane Eyre"
                        },
                        new
                        {
                            Id = new Guid("f3c88511-64f1-43ea-9943-4d2b019c0fe8"),
                            Author = "Emily Bronte",
                            Category = "Novel",
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = new Guid("35e281d5-933c-4609-bb6e-faf5d3a05e12"),
                            Author = "J. R. R. Tolkien",
                            Category = "Fantasy",
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("0c6a48c5-e5a8-4c57-bd7e-83b5ffcdb51b"),
                            Author = "J. R. R. Tolkien",
                            Category = "Fantasy",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("7e2ab259-b14b-457a-8b0a-d65fa2fc6d11"),
                            Author = "C. S. Lewis",
                            Category = "Fantasy",
                            Title = "The Lion, the Witch and the Wardrobe"
                        },
                        new
                        {
                            Id = new Guid("1e71a2a1-2e76-4869-b6b8-27cbef202b13"),
                            Author = "Dan Brown",
                            Category = "Mystery",
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = new Guid("0f837890-cea3-41aa-a1e1-62290e1b774d"),
                            Author = "Dan Brown",
                            Category = "Mystery",
                            Title = "Angels & Demons"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6296d867-8e4e-4d08-9ce1-e1bf11dd0d50"),
                            Cc = "CNY",
                            Rate = 5.7923f,
                            Text = "Юань Женьміньбі"
                        },
                        new
                        {
                            Id = new Guid("92be0ad0-f658-4bac-9637-337d2ecc2600"),
                            Cc = "CZK",
                            Rate = 1.8184f,
                            Text = "Чеська крона"
                        },
                        new
                        {
                            Id = new Guid("daec79e8-7e05-40ac-878d-cc50beb2ce4d"),
                            Cc = "DKK",
                            Rate = 6.1005f,
                            Text = "Данська крона"
                        },
                        new
                        {
                            Id = new Guid("c13757c2-048e-4468-ac78-c69b1251dd71"),
                            Cc = "HKD",
                            Rate = 5.2657f,
                            Text = "Гонконгівський долар"
                        },
                        new
                        {
                            Id = new Guid("31d1b090-283a-4784-a43b-13fbfac5e6f4"),
                            Cc = "IDR",
                            Rate = 0.0026562f,
                            Text = "Рупія"
                        },
                        new
                        {
                            Id = new Guid("015cb52c-285a-410e-92fd-7b017b43dd53"),
                            Cc = "ILS",
                            Rate = 11.3011f,
                            Text = "Новий ізраїльський шекель"
                        },
                        new
                        {
                            Id = new Guid("4f883754-89bb-4ca7-a7d5-1fb66f924e01"),
                            Cc = "JPY",
                            Rate = 0.28234f,
                            Text = "Єна"
                        },
                        new
                        {
                            Id = new Guid("977786d2-c4c3-436d-8413-93948767d5b9"),
                            Cc = "KZT",
                            Rate = 0.085217f,
                            Text = "Теньге"
                        },
                        new
                        {
                            Id = new Guid("fa24f63e-481a-4bc2-88ba-3431cbc8f1ce"),
                            Cc = "MXN",
                            Rate = 2.0898f,
                            Text = "Мексиканське песо"
                        },
                        new
                        {
                            Id = new Guid("0d7ae1b7-e52f-410f-b0b9-7f55f250e8b4"),
                            Cc = "MDL",
                            Rate = 2.3611f,
                            Text = "Молдовський лей"
                        },
                        new
                        {
                            Id = new Guid("956d4454-c7b2-46cb-8640-f4a7f50ae423"),
                            Cc = "NZD",
                            Rate = 25.6948f,
                            Text = "Новозеландський долар"
                        },
                        new
                        {
                            Id = new Guid("0be052d1-96e8-4d73-a378-da34f64c52c2"),
                            Cc = "NOK",
                            Rate = 3.9006f,
                            Text = "Норвезька крона"
                        },
                        new
                        {
                            Id = new Guid("e18025aa-e7db-4fda-86bb-850be5559090"),
                            Cc = "SGD",
                            Rate = 31.5185f,
                            Text = "Сінгапурський долар"
                        },
                        new
                        {
                            Id = new Guid("bff0ba98-78f3-4cb1-9b58-9778c041b23f"),
                            Cc = "SEK",
                            Rate = 4.012f,
                            Text = "Шведська крона"
                        },
                        new
                        {
                            Id = new Guid("c3ff3cd6-19e3-4bc2-822c-046928324ab8"),
                            Cc = "CHF",
                            Rate = 48.3362f,
                            Text = "Швейцарський франк"
                        },
                        new
                        {
                            Id = new Guid("5d2d6ada-e568-4180-957c-6afc71b581b1"),
                            Cc = "GBP",
                            Rate = 54.1181f,
                            Text = "Фунт стерлінгів"
                        },
                        new
                        {
                            Id = new Guid("5a9e7b69-f875-422b-b2de-db3e6defebc0"),
                            Cc = "USD",
                            Rate = 41.0592f,
                            Text = "Долар США"
                        },
                        new
                        {
                            Id = new Guid("02ab21a1-6b36-46ed-a14d-4aa530621836"),
                            Cc = "AZN",
                            Rate = 24.1539f,
                            Text = "Азербайджанський манат"
                        },
                        new
                        {
                            Id = new Guid("e9a8bd02-b4d3-4c3d-ab56-1ef48b51efed"),
                            Cc = "TRY",
                            Rate = 1.2053f,
                            Text = "Турецька ліра"
                        },
                        new
                        {
                            Id = new Guid("4c5b0c7b-5ac9-44e3-81f9-711a9863b1c8"),
                            Cc = "EUR",
                            Rate = 45.5018f,
                            Text = "Євро"
                        },
                        new
                        {
                            Id = new Guid("89db4e6b-fd6c-4b05-8cdf-26f5fb28131d"),
                            Cc = "PLN",
                            Rate = 10.6354f,
                            Text = "Злотий"
                        },
                        new
                        {
                            Id = new Guid("aa25607d-f23f-478e-977e-e32621efa0e1"),
                            Cc = "AMD",
                            Rate = 0.105951f,
                            Text = "Вірменський драм"
                        },
                        new
                        {
                            Id = new Guid("509be7ed-c39b-4003-b79a-e80af6616f92"),
                            Cc = "DOP",
                            Rate = 0.69143f,
                            Text = "Домініканське песо"
                        },
                        new
                        {
                            Id = new Guid("51d373d0-1716-4cb0-83c6-c4de3494c14f"),
                            Cc = "LBP",
                            Rate = 0.000459f,
                            Text = "Ліванський фунт"
                        },
                        new
                        {
                            Id = new Guid("875bdd53-d35d-4156-b4a4-f5bcc22ea0fe"),
                            Cc = "PKR",
                            Rate = 0.14738f,
                            Text = "Пакистанська рупія"
                        },
                        new
                        {
                            Id = new Guid("d6e5a0d2-8625-41f7-8345-7a97d91d326b"),
                            Cc = "SAR",
                            Rate = 10.9412f,
                            Text = "Саудівський ріял"
                        },
                        new
                        {
                            Id = new Guid("1f6f872b-f999-4490-a2fe-caa1d563176b"),
                            Cc = "THB",
                            Rate = 1.21201f,
                            Text = "Бат"
                        },
                        new
                        {
                            Id = new Guid("63082b2e-cf42-4b9d-8cc6-eb6a95155db4"),
                            Cc = "AED",
                            Rate = 11.179f,
                            Text = "Дирхам ОАЕ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
