// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(CarsContext))]
    partial class CarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29491c70-d077-4bcc-ab40-c92f6882563c"),
                            Brand = "Toyota",
                            Model = "Camry",
                            Price = 25000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("0d473d3d-aead-45c9-8401-453ce9f52600"),
                            Brand = "Toyota",
                            Model = "Corolla",
                            Price = 20000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("ae9ff982-79cd-485f-bb80-da1495199bdc"),
                            Brand = "Ford",
                            Model = "Focus",
                            Price = 22000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("a9d7bf01-f7f6-4931-9b03-fcf770cefee2"),
                            Brand = "Ford",
                            Model = "Fusion",
                            Price = 25000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("f213cbe1-c3ae-493f-a9bb-89cc073950c6"),
                            Brand = "Chevrolet",
                            Model = "Cruze",
                            Price = 23000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("52f58da2-778d-49a7-a1ec-19c072ba7b68"),
                            Brand = "Chevrolet",
                            Model = "Malibu",
                            Price = 28000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("0efd3ea5-96f3-4b0f-8c6f-ee3120911730"),
                            Brand = "BMW",
                            Model = "X5",
                            Price = 60000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("5a29df10-ee73-4156-8dba-6c093b731a63"),
                            Brand = "BMW",
                            Model = "X6",
                            Price = 65000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("16205268-2849-4c47-a666-4f11ee7ee7a4"),
                            Brand = "Honda",
                            Model = "Accord",
                            Price = 30000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("17370ada-d939-4740-90ea-629aeea1ec7e"),
                            Brand = "Honda",
                            Model = "Civic",
                            Price = 25000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("340f9688-e61c-4636-bea6-10fdd7859c89"),
                            Brand = "Volkswagen",
                            Model = "Golf",
                            Price = 22000L,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("921e45a8-47ed-4855-931e-9663f84d91c5"),
                            Brand = "Volkswagen",
                            Model = "Jetta",
                            Price = 25000L,
                            Year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
